language: c

git:
  depth: 1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8-multilib
    - linux-libc-dev:i386

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq libX11-dev:i386

script:
  - cd Modelica_DeviceDrivers/Resources
  # 32bit:
  - cmake -DCMAKE_C_COMPILER="gcc-4.8" -DCMAKE_C_FLAGS="-O3 -msse2 -DNDEBUG -m32 -fPIC" ./
  - make
  - cd test/Util
  - ./test_MDDMapIntInt
  - ./test_MDDMapIntpVoid
  - ./test_MDDUtilities
  - cd ../OperatingSystem
  - ./test_MDD_getTimeMS
  - sudo ./test_MDDRealtimeSynchronize_high
  - ./test_MDDRealtimeSynchronize_idle
  - ./test_MDDRealtimeSynchronize_low
  - ./test_MDDRealtimeSynchronize_normal
  - cd ../Communication
  - ./test_EndiannessConversion
  - ./test_MDDSerialPackager
  - ./test_MDDSharedMemory
  - ./test_MDDUDPSocket
  - cd ../..
  # 64bit:
  - cmake -DCMAKE_C_COMPILER="gcc-4.8" -DCMAKE_C_FLAGS="-O3 -DNDEBUG -fPIC" ./
  - make
  - cd test/Util
  - ./test_MDDMapIntInt
  - ./test_MDDMapIntpVoid
  - ./test_MDDUtilities
  - cd ../OperatingSystem
  - ./test_MDD_getTimeMS
  - sudo ./test_MDDRealtimeSynchronize_high
  - ./test_MDDRealtimeSynchronize_idle
  - ./test_MDDRealtimeSynchronize_low
  - ./test_MDDRealtimeSynchronize_normal
  - cd ../Communication
  - ./test_EndiannessConversion
  - ./test_MDDSerialPackager
  - ./test_MDDSharedMemory
  - ./test_MDDUDPSocket
  - cd ../..

notifications:
  email: false

# sudo: false
